services:
  postgres-db:
    image: postgres:17.5-alpine
    container_name: appeal-system-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-appeal_system_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-appeal_system_password}
      POSTGRES_DB: ${POSTGRES_DB:-appeal_system_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: