spring:
  application:
    name: appeal-system

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    username: ${POSTGRES_USER:appeal_system_user}
    password: ${POSTGRES_PASSWORD:appeal_system_password}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/appeal_system_db}

appeal-system:
  emojis:
    roblox: <:name:id>

  games:
    - name:
      crossroad-description:
        -
        -
        -
      image:
      appeal-server-id:
      community-server-id: